version: "3.0"

services:
  testui:
    build:
      context: ./docker/testui
    image: cfwheels-testui:v1.0.2
    ports:
      - "3000:8080"

  lucee5:
    build:
      context: ./
      dockerfile: ./docker/lucee@5/Dockerfile
    image: cfwheels-test-lucee5:v1.0.2
    volumes:
      - ./:/cfwheels-test-suite
      - ~/.CommandBox/artifacts:/root/.CommandBox/artifacts
      - type: bind
        source: ./docker/lucee@5/server.json
        target: /cfwheels-test-suite/server.json
      - type: bind
        source: ./docker/lucee@5/settings.cfm
        target: /cfwheels-test-suite/app/config/settings.cfm
    ports:
      - "60005:60005"

  lucee6:
    build:
      context: ./
      dockerfile: ./docker/lucee@6/Dockerfile
    image: cfwheels-test-lucee6:v1.0.2
    volumes:
      - ./:/cfwheels-test-suite
      - ~/.CommandBox/artifacts:/root/.CommandBox/artifacts
      - type: bind
        source: ./docker/lucee@6/server.json
        target: /cfwheels-test-suite/server.json
      - type: bind
        source: ./docker/lucee@6/settings.cfm
        target: /cfwheels-test-suite/app/config/settings.cfm
    ports:
      - "60006:60006"

  adobe2018:
    build:
      context: ./
      dockerfile: ./docker/adobe@2018/Dockerfile
    image: cfwheels-test-adobe2018:v1.0.2
    volumes:
      - ./:/cfwheels-test-suite
      - ~/.CommandBox/artifacts:/root/.CommandBox/artifacts
      - type: bind
        source: ./docker/adobe@2018/server.json
        target: /cfwheels-test-suite/server.json
      - type: bind
        source: ./docker/adobe@2018/settings.cfm
        target: /cfwheels-test-suite/app/config/settings.cfm
    ports:
      - "62018:62018"

  adobe2021:
    build:
      context: ./
      dockerfile: ./docker/adobe@2021/Dockerfile
    image: cfwheels-test-adobe2021:v1.0.2
    volumes:
      - ./:/cfwheels-test-suite
      - ~/.CommandBox/artifacts:/root/.CommandBox/artifacts
      - type: bind
        source: ./docker/adobe@2021/server.json
        target: /cfwheels-test-suite/server.json
      - type: bind
        source: ./docker/adobe@2021/settings.cfm
        target: /cfwheels-test-suite/app/config/settings.cfm
    ports:
      - "62021:62021"

  adobe2023:
    build:
      context: ./
      dockerfile: ./docker/adobe@2023/Dockerfile
    image: cfwheels-test-adobe2023:v1.0.1
    volumes:
      - ./:/cfwheels-test-suite
      - ~/.CommandBox/artifacts:/root/.CommandBox/artifacts
      - type: bind
        source: ./docker/adobe@2023/server.json
        target: /cfwheels-test-suite/server.json
      - type: bind
        source: ./docker/adobe@2023/settings.cfm
        target: /cfwheels-test-suite/app/config/settings.cfm
    ports:
      - "62023:62023"

  mysql:
    image: mysql:latest
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wheelstestdb
      MYSQL_DATABASE: wheelstestdb
      MYSQL_USER: wheelstestdb
      MYSQL_PASSWORD: wheelstestdb
    ports:
      - "3307:3306"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: wheelstestdb
      POSTGRES_PASSWORD: wheelstestdb
      POSTGRES_INITDB_ARGS: --auth-host=md5
    ports:
      - "5433:5432"

  sqlserver:
    build:
      context: ./
      dockerfile: ./docker/sqlserver/Dockerfile
    image: cfwheels-sqlserver:v1.0.1
    environment:
      MSSQL_SA_PASSWORD: x!bsT8t60yo0cTVTPq
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
    ports:
      - "1434:1433"